### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Tom-van-Grinsven** [morkro/happy-plants#105]
Not really an issue and forgive me if im asking something that you dont want to tell. I want to create something similar to your app for hobby purposes. I was wondering how you get your plant data. I see you have a database located at https://happy-plants-app.firebaseio.com but how did you populate that database with data? Did you insert it all by hand or is there some API you used?

**Comment by morkro** [comment]
Hey @Tom-van-Grinsven! I don't really have a plant database, it's all user created content.  If you're looking for a plant database, then https://trefle.io/ might be interesting to you. I am also planning to integrate it at some point.
