### ISSUE TITLE
Don’t use `hidden` for assisting text

### ISSUE THREAD

**Issue by HugoGiraudel** [morkro/happy-plants#39]
The `hidden` attribute hides something both visually **and** from the accessibility tree, therefore should *not* be used to hide assisting text (as done for the settings button).

To hide an element visually while keeping it accessible in the AT, something like described in this article: https://hugogiraudel.com/2016/10/13/css-hide-and-seek/. Or use `aria-label` (although it also comes with its own drawbacks).

**Comment by morkro** [comment]
This has been fixed in a couple of earlier releases by now :)
